[tox]
envlist = lint, sanity
min_version = 4.0

[testenv:lint]
deps =
    ansible-lint
commands =
    ansible-lint {toxinidir}

[testenv:sanity]
deps =
    ansible-core>=2.16
commands =
    ansible-test sanity --local -v --color --python {basepython}

[testenv:bandit]
deps =
    bandit
commands =
    bandit -r {toxinidir}/plugins/ -ll -ii
