---
- name: "Truenas Alert Remediation"
  hosts: all
  sources:
    - stevefulme1.truenas.truenas_webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Critical alert
      condition: event.truenas is defined
      action:
        run_playbook:
          name: remediate.yml
          extra_vars:
            alert: "{{ event.truenas }}"
